### ISSUE TITLE
Guids

### ISSUE THREAD

**Issue by apenalver2** [systelab/systelab-preferences#33]
As part of the utilities, will be interesting functionality to generate new guides, check if the Guid is empty, or return an empty Guid.
![image](https://user-images.githubusercontent.com/34027110/110302738-db6efb80-7ff9-11eb-939a-4d9147a3c7e0.png)

**Comment by olgapuig** [comment]
It would be better to review if there's an standard way already build.

**Comment by oshura** [comment]
Hello @olgapuig. I'm creating a set of classes that will use uuid package (https://www.npmjs.com/package/uuid) and implement GUID generation over it.
The point of this comment is that this functionality would be better if belongs to systelab-components. Even thou, it's not a component, but a crosscutting functionallity.
For now, I'll continue under \src\lib\guid at systelab-components by opening a related issue, if no new proposal comes up.

**Comment by olgapuig** [comment]
Hi @oshura, I recommend to raise this question in the TF Angular technical chat. Anyway, this can be reviewed in the next backlog grooming on Dec 13.

**Comment by olgapuig** [comment]
Backlog grooming 13/12. This issue is rejected
