### ISSUE TITLE
CopyToClipBoard

### ISSUE THREAD

**Issue by apenalver2** [systelab/systelab-preferences#37]
Include the functionality to copy a text to the clipboard of the browser.
Example: 
![image](https://user-images.githubusercontent.com/34027110/110767013-13727a80-8256-11eb-97e1-a62eb774364b.png)

**Comment by olgapuig** [comment]
This util can be used from the systelab-components library. An option is to add a copy option with the behaviour.

**Comment by olgapuig** [comment]
Move this to systelab-components

**Comment by apenalver2** [comment]
Moved to Systelab-Components #441
